#############################################################################
# Makefile for building: calcul-mental-master
# Generated by qmake (2.01a) (Qt 4.6.3) on: Mon Jan 30 10:05:23 2012
# Project:  calcul-mental-master.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile calcul-mental-master.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Bilan.cpp \
		Boite.cpp \
		Deduction.cpp \
		DroiteG.cpp \
		Equation.cpp \
		Exercice.cpp \
		ExerciceSerie.cpp \
		Grad.cpp \
		main.cpp \
		Menu.cpp \
		Monome.cpp \
		Table.cpp moc_Boite.cpp \
		moc_Deduction.cpp \
		moc_Equation.cpp \
		moc_Exercice.cpp \
		moc_ExerciceSerie.cpp \
		moc_Grad.cpp \
		moc_Menu.cpp \
		moc_Table.cpp
OBJECTS       = Bilan.o \
		Boite.o \
		Deduction.o \
		DroiteG.o \
		Equation.o \
		Exercice.o \
		ExerciceSerie.o \
		Grad.o \
		main.o \
		Menu.o \
		Monome.o \
		Table.o \
		moc_Boite.o \
		moc_Deduction.o \
		moc_Equation.o \
		moc_Exercice.o \
		moc_ExerciceSerie.o \
		moc_Grad.o \
		moc_Menu.o \
		moc_Table.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		calcul-mental-master.pro
QMAKE_TARGET  = calcul-mental-master
DESTDIR       = 
TARGET        = calcul-mental-master

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: calcul-mental-master.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile calcul-mental-master.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile calcul-mental-master.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/calcul-mental-master1.0.0 || $(MKDIR) .tmp/calcul-mental-master1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/calcul-mental-master1.0.0/ && $(COPY_FILE) --parents Bilan.h Boite.h Deduction.h DroiteG.h Equation.h Exercice.h ExerciceSerie.h Grad.h Menu.h Monome.h Table.h .tmp/calcul-mental-master1.0.0/ && $(COPY_FILE) --parents Bilan.cpp Boite.cpp Deduction.cpp DroiteG.cpp Equation.cpp Exercice.cpp ExerciceSerie.cpp Grad.cpp main.cpp Menu.cpp Monome.cpp Table.cpp .tmp/calcul-mental-master1.0.0/ && (cd `dirname .tmp/calcul-mental-master1.0.0` && $(TAR) calcul-mental-master1.0.0.tar calcul-mental-master1.0.0 && $(COMPRESS) calcul-mental-master1.0.0.tar) && $(MOVE) `dirname .tmp/calcul-mental-master1.0.0`/calcul-mental-master1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/calcul-mental-master1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Boite.cpp moc_Deduction.cpp moc_Equation.cpp moc_Exercice.cpp moc_ExerciceSerie.cpp moc_Grad.cpp moc_Menu.cpp moc_Table.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Boite.cpp moc_Deduction.cpp moc_Equation.cpp moc_Exercice.cpp moc_ExerciceSerie.cpp moc_Grad.cpp moc_Menu.cpp moc_Table.cpp
moc_Boite.cpp: Exercice.h \
		Bilan.h \
		Boite.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Boite.h -o moc_Boite.cpp

moc_Deduction.cpp: Exercice.h \
		Bilan.h \
		Deduction.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Deduction.h -o moc_Deduction.cpp

moc_Equation.cpp: Monome.h \
		Exercice.h \
		Bilan.h \
		Equation.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Equation.h -o moc_Equation.cpp

moc_Exercice.cpp: Bilan.h \
		Exercice.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Exercice.h -o moc_Exercice.cpp

moc_ExerciceSerie.cpp: Exercice.h \
		Bilan.h \
		ExerciceSerie.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ExerciceSerie.h -o moc_ExerciceSerie.cpp

moc_Grad.cpp: Exercice.h \
		Bilan.h \
		Grad.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Grad.h -o moc_Grad.cpp

moc_Menu.cpp: ExerciceSerie.h \
		Exercice.h \
		Bilan.h \
		Boite.h \
		Table.h \
		Deduction.h \
		Grad.h \
		Equation.h \
		Monome.h \
		Menu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Menu.h -o moc_Menu.cpp

moc_Table.cpp: Exercice.h \
		Bilan.h \
		Table.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Table.h -o moc_Table.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Bilan.o: Bilan.cpp Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bilan.o Bilan.cpp

Boite.o: Boite.cpp Boite.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Boite.o Boite.cpp

Deduction.o: Deduction.cpp Deduction.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deduction.o Deduction.cpp

DroiteG.o: DroiteG.cpp DroiteG.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DroiteG.o DroiteG.cpp

Equation.o: Equation.cpp Equation.h \
		Monome.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Equation.o Equation.cpp

Exercice.o: Exercice.cpp Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Exercice.o Exercice.cpp

ExerciceSerie.o: ExerciceSerie.cpp ExerciceSerie.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExerciceSerie.o ExerciceSerie.cpp

Grad.o: Grad.cpp Grad.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grad.o Grad.cpp

main.o: main.cpp Menu.h \
		ExerciceSerie.h \
		Exercice.h \
		Bilan.h \
		Boite.h \
		Table.h \
		Deduction.h \
		Grad.h \
		Equation.h \
		Monome.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Menu.o: Menu.cpp Menu.h \
		ExerciceSerie.h \
		Exercice.h \
		Bilan.h \
		Boite.h \
		Table.h \
		Deduction.h \
		Grad.h \
		Equation.h \
		Monome.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Menu.o Menu.cpp

Monome.o: Monome.cpp Monome.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Monome.o Monome.cpp

Table.o: Table.cpp Table.h \
		Exercice.h \
		Bilan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Table.o Table.cpp

moc_Boite.o: moc_Boite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Boite.o moc_Boite.cpp

moc_Deduction.o: moc_Deduction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Deduction.o moc_Deduction.cpp

moc_Equation.o: moc_Equation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Equation.o moc_Equation.cpp

moc_Exercice.o: moc_Exercice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Exercice.o moc_Exercice.cpp

moc_ExerciceSerie.o: moc_ExerciceSerie.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ExerciceSerie.o moc_ExerciceSerie.cpp

moc_Grad.o: moc_Grad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Grad.o moc_Grad.cpp

moc_Menu.o: moc_Menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Menu.o moc_Menu.cpp

moc_Table.o: moc_Table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Table.o moc_Table.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

